/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene-unmerged.glb -o SceneWithPhone.tsx -T --types 
Files: scene-unmerged.glb [1.6MB] > /Users/haukesandhaus/Documents/GitHub/Vibe-Coding-Class/website/assets/scene-unmerged-transformed.glb [128.65KB] (92%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Blank_Picture_Frame|Node007|Dupli|']: THREE.Mesh
    ['cornell-tech-sky']: THREE.Mesh
    ['VAP-cover']: THREE.Mesh
    Message_Board: THREE.Mesh
    ['Monitor001|iMac|Dupli|']: THREE.Mesh
    Monitor_Plane: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    ['cornell-tech-sky']: THREE.MeshStandardMaterial
    ['VAP-cover']: THREE.MeshStandardMaterial
    Mat: THREE.MeshStandardMaterial
    ['Mat.008']: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene-unmerged-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={44.096} position={[-1.773, 1.589, 1.109]} rotation={[-0.693, -0.754, -0.517]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={44.096} position={[-1.5, 1, 0]} rotation={[-Math.PI / 2, -1.501, -Math.PI / 2]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={44.096} position={[-1.017, 1.211, -0.155]} rotation={[-Math.PI / 2, -1.501, -Math.PI / 2]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={44.096} position={[-0.645, 1.058, -0.449]} rotation={[-1.539, -0.348, -1.164]} />
      <mesh geometry={nodes['Blank_Picture_Frame|Node007|Dupli|'].geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes['cornell-tech-sky'].geometry} material={materials['cornell-tech-sky']} />
      <mesh geometry={nodes['VAP-cover'].geometry} material={materials['VAP-cover']} />
      <mesh geometry={nodes.Message_Board.geometry} material={materials.Mat} />
      <mesh geometry={nodes['Monitor001|iMac|Dupli|'].geometry} material={materials['Mat.008']} />
      <mesh geometry={nodes.Monitor_Plane.geometry} material={materials.PaletteMaterial002} />
    </group>
  )
}

useGLTF.preload('/scene-unmerged-transformed.glb')
