// Student submissions — live sites for each activity, plus group projects.
//
// ACTIVITIES: every student's fork deploys to
//   https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-<handle>/<week>/<day>/code_deliverable/
// Only submissions that are actually built are listed — untouched starter
// placeholders are filtered out. Re-generate after each class with:
//   bash scripts/refresh-submissions.sh   (writes this file; review the diff)
//
// `title` is scraped from each page's <title>. Student display names are
// hand-mapped from the roster — fix any that read wrong, they're just strings.

export const SUBMISSION_SETS = [
    {
        id: "week1-7_13", kind: 'activity', chip: "W1 Mon", day: "Mon · Jul 13", title: "Personal Portfolio",
        entries: [
            { id: "ay487-maker", student: "Ajin Yohannan", title: "About Me · Ajin Yohannan", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-ay487-maker/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-ay487-maker/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-ay487-maker%2Fweek1%2F7_13%2Fvibe-report.md&title=Ajin+Yohannan+%E2%80%94+vibe+report" },
            { id: "ds2553", student: "Derin Sezgin", title: "Derin Ege Sezgin | SDG Youth Connect", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-ds2553/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-ds2553/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-ds2553%2Fweek1%2F7_13%2Fvibe-report.md&title=Derin+Sezgin+%E2%80%94+vibe+report" },
            { id: "c28eh-eng", student: "Elaine Huang", title: "Elaine Huang", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-c28eh-eng/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-c28eh-eng/tree/main/week1/7_13" },
            { id: "et483-sys", student: "Emily Tai", title: "Emily | Personal Website", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-et483-sys/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-et483-sys/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-et483-sys%2Fweek1%2F7_13%2Fvibe-report.md&title=Emily+Tai+%E2%80%94+vibe+report" },
            { id: "eb886-ops", student: "Evan Birnbaum", title: "About Evan · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-eb886-ops/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-eb886-ops/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-eb886-ops%2Fweek1%2F7_13%2Fvibe-report.md&title=Evan+Birnbaum+%E2%80%94+vibe+report" },
            { id: "isaiah-coder11", student: "Isa Offengenden", title: "Isa-Offengenden's bio · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-isaiah-coder11/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-isaiah-coder11/tree/main/week1/7_13" },
            { id: "br478-spec", student: "Jamin Rose", title: "Benjamin Jamin Rose · Portfolio Page", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-br478-spec/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-br478-spec/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-br478-spec%2Fweek1%2F7_13%2Fvibe-report.md&title=Jamin+Rose+%E2%80%94+vibe+report" },
            { id: "jason-chen3968", student: "Jason Chen", title: "Jason Chen | About Me", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-jason-chen3968/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-jason-chen3968/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-jason-chen3968%2Fweek1%2F7_13%2Fvibe-report.md&title=Jason+Chen+%E2%80%94+vibe+report" },
            { id: "JohnM-code", student: "John Maida", title: "John Maida · Personal Page", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-JohnM-code/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-JohnM-code/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-JohnM-code%2Fweek1%2F7_13%2Fvibe-report.md&title=John+Maida+%E2%80%94+vibe+report" },
            { id: "oujustinou", student: "Justin Ou", title: "Justin Ou — About Me", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oujustinou/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-oujustinou/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-oujustinou%2Fweek1%2F7_13%2Fvibe-report.md&title=Justin+Ou+%E2%80%94+vibe+report" },
            { id: "kc2386-rgb", student: "Kylie Cheung", title: "Kylie Cheung · Personal Website", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-kc2386-rgb/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-kc2386-rgb/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-kc2386-rgb%2Fweek1%2F7_13%2Fvibe-report.md&title=Kylie+Cheung+%E2%80%94+vibe+report" },
            { id: "la523-tech", student: "Liam Allen", title: "Liam Allen | Portfolio", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-la523-tech/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-la523-tech/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-la523-tech%2Fweek1%2F7_13%2Fvibe-report.md&title=Liam+Allen+%E2%80%94+vibe+report" },
            { id: "md2367-888", student: "Magnes Dugan", title: "Magnes Dugan · Personal Website", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-md2367-888/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-md2367-888/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-md2367-888%2Fweek1%2F7_13%2Fvibe-report.md&title=Magnes+Dugan+%E2%80%94+vibe+report" },
            { id: "oliverc70", student: "Oliver Chung", title: "About Oliver Chung", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oliverc70/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-oliverc70/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-oliverc70%2Fweek1%2F7_13%2Fvibe-report.md&title=Oliver+Chung+%E2%80%94+vibe+report" },
            { id: "or2270", student: "Om Ravula", title: "Week 1 - 7/13", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-or2270/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-or2270/tree/main/week1/7_13" },
            { id: "sg2697-ux", student: "Sebastien Gournay", title: "Sebastien Gournay · About Me", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-sg2697-ux/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-sg2697-ux/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-sg2697-ux%2Fweek1%2F7_13%2Fvibe-report.md&title=Sebastien+Gournay+%E2%80%94+vibe+report" },
            { id: "vienna-carew", student: "Vienna Carew", title: "Vienna Carew · Personal Website", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-vienna-carew/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-vienna-carew/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-vienna-carew%2Fweek1%2F7_13%2Fvibe-report.md&title=Vienna+Carew+%E2%80%94+vibe+report" },
            { id: "winnie-monroe", student: "Winnie Monroe", title: "Winnie Monroe · About Me", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-winnie-monroe/week1/7_13/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-winnie-monroe/tree/main/week1/7_13", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-winnie-monroe%2Fweek1%2F7_13%2Fvibe-report.md&title=Winnie+Monroe+%E2%80%94+vibe+report" }
        ],
    },
    {
        id: "week1-7_14", kind: 'activity', chip: "W1 Tue", day: "Tue · Jul 14", title: "Prompt Engineering",
        entries: [
            { id: "ay487-maker", student: "Ajin Yohannan", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-ay487-maker/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-ay487-maker/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-ay487-maker%2Fweek1%2F7_14%2Fvibe-report.md&title=Ajin+Yohannan+%E2%80%94+vibe+report" },
            { id: "as4663-hash", student: "Aria Sharma", title: "Lawrenceville Club Finder · Version Overview", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-as4663-hash/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-as4663-hash/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-as4663-hash%2Fweek1%2F7_14%2Fvibe-report.md&title=Aria+Sharma+%E2%80%94+vibe+report" },
            { id: "ds2553", student: "Derin Sezgin", title: "Prompt Comparison Gallery", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-ds2553/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-ds2553/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-ds2553%2Fweek1%2F7_14%2Fvibe-report.md&title=Derin+Sezgin+%E2%80%94+vibe+report" },
            { id: "c28eh-eng", student: "Elaine Huang", title: "Pixel Art Maker", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-c28eh-eng/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-c28eh-eng/tree/main/week1/7_14" },
            { id: "et483-sys", student: "Emily Tai", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-et483-sys/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-et483-sys/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-et483-sys%2Fweek1%2F7_14%2Fvibe-report.md&title=Emily+Tai+%E2%80%94+vibe+report" },
            { id: "eb886-ops", student: "Evan Birnbaum", title: "Daily Pomodoro Timer", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-eb886-ops/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-eb886-ops/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-eb886-ops%2Fweek1%2F7_14%2Fvibe-report.md&title=Evan+Birnbaum+%E2%80%94+vibe+report" },
            { id: "isaiah-coder11", student: "Isa Offengenden", title: "Magic 8 Ball", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-isaiah-coder11/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-isaiah-coder11/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-isaiah-coder11%2Fweek1%2F7_14%2Fvibe-report.md&title=Isa+Offengenden+%E2%80%94+vibe+report" },
            { id: "br478-spec", student: "Jamin Rose", title: "Recovery Log · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-br478-spec/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-br478-spec/tree/main/week1/7_14" },
            { id: "jason-chen3968", student: "Jason Chen", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-jason-chen3968/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-jason-chen3968/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-jason-chen3968%2Fweek1%2F7_14%2Fvibe-report.md&title=Jason+Chen+%E2%80%94+vibe+report" },
            { id: "JohnM-code", student: "John Maida", title: "Prompt Engineering — versions", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-JohnM-code/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-JohnM-code/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-JohnM-code%2Fweek1%2F7_14%2Fvibe-report.md&title=John+Maida+%E2%80%94+vibe+report" },
            { id: "oujustinou", student: "Justin Ou", title: "Pomodoro + Chess", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oujustinou/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-oujustinou/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-oujustinou%2Fweek1%2F7_14%2Fvibe-report.md&title=Justin+Ou+%E2%80%94+vibe+report" },
            { id: "kc2386-rgb", student: "Kylie Cheung", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-kc2386-rgb/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-kc2386-rgb/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-kc2386-rgb%2Fweek1%2F7_14%2Fvibe-report.md&title=Kylie+Cheung+%E2%80%94+vibe+report" },
            { id: "la523-tech", student: "Liam Allen", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-la523-tech/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-la523-tech/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-la523-tech%2Fweek1%2F7_14%2Fvibe-report.md&title=Liam+Allen+%E2%80%94+vibe+report" },
            { id: "md2367-888", student: "Magnes Dugan", title: "Week 1 Day 4 — 7_14 Pages", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-md2367-888/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-md2367-888/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-md2367-888%2Fweek1%2F7_14%2Fvibe-report.md&title=Magnes+Dugan+%E2%80%94+vibe+report" },
            { id: "oliverc70", student: "Oliver Chung", title: "Chill Clock Toggle", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oliverc70/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-oliverc70/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-oliverc70%2Fweek1%2F7_14%2Fvibe-report.md&title=Oliver+Chung+%E2%80%94+vibe+report" },
            { id: "or2270", student: "Om Ravula", title: "Prompt Engineering Lab", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-or2270/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-or2270/tree/main/week1/7_14" },
            { id: "sg2697-ux", student: "Sebastien Gournay", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-sg2697-ux/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-sg2697-ux/tree/main/week1/7_14" },
            { id: "vienna-carew", student: "Vienna Carew", title: "Rainy Café Prompt Gallery", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-vienna-carew/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-vienna-carew/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-vienna-carew%2Fweek1%2F7_14%2Fvibe-report.md&title=Vienna+Carew+%E2%80%94+vibe+report" },
            { id: "winnie-monroe", student: "Winnie Monroe", title: "Pomodoro Timer", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-winnie-monroe/week1/7_14/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-winnie-monroe/tree/main/week1/7_14", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-winnie-monroe%2Fweek1%2F7_14%2Fvibe-report.md&title=Winnie+Monroe+%E2%80%94+vibe+report" }
        ],
    },
    {
        id: "week1-7_15", kind: 'activity', chip: "W1 Wed", day: "Wed · Jul 15", title: "Comparing Tools",
        entries: [
            { id: "ay487-maker", student: "Ajin Yohannan", title: "Comparing AI Tools — chemistry quiz", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-ay487-maker/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-ay487-maker/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-ay487-maker%2Fweek1%2F7_15%2Fvibe-report.md&title=Ajin+Yohannan+%E2%80%94+vibe+report" },
            { id: "as4663-hash", student: "Aria Sharma", title: "Whose Defaults? | Vibe Coding Comparison", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-as4663-hash/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-as4663-hash/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-as4663-hash%2Fweek1%2F7_15%2Fvibe-report.md&title=Aria+Sharma+%E2%80%94+vibe+report" },
            { id: "ds2553", student: "Derin Sezgin", title: "Week 1 Day 3 · Galatasaray Fan Experience", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-ds2553/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-ds2553/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-ds2553%2Fweek1%2F7_15%2Fvibe-report.md&title=Derin+Sezgin+%E2%80%94+vibe+report" },
            { id: "c28eh-eng", student: "Elaine Huang", title: "Comparing AI Tools — step by step", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-c28eh-eng/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-c28eh-eng/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-c28eh-eng%2Fweek1%2F7_15%2Fvibe-report.md&title=Elaine+Huang+%E2%80%94+vibe+report" },
            { id: "et483-sys", student: "Emily Tai", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-et483-sys/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-et483-sys/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-et483-sys%2Fweek1%2F7_15%2Fvibe-report.md&title=Emily+Tai+%E2%80%94+vibe+report" },
            { id: "eb886-ops", student: "Evan Birnbaum", title: "AI Tool Pages", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-eb886-ops/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-eb886-ops/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-eb886-ops%2Fweek1%2F7_15%2Fvibe-report.md&title=Evan+Birnbaum+%E2%80%94+vibe+report" },
            { id: "isaiah-coder11", student: "Isa Offengenden", title: "Interactive Quiz App", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-isaiah-coder11/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-isaiah-coder11/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-isaiah-coder11%2Fweek1%2F7_15%2Fvibe-report.md&title=Isa+Offengenden+%E2%80%94+vibe+report" },
            { id: "br478-spec", student: "Jamin Rose", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-br478-spec/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-br478-spec/tree/main/week1/7_15" },
            { id: "jason-chen3968", student: "Jason Chen", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-jason-chen3968/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-jason-chen3968/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-jason-chen3968%2Fweek1%2F7_15%2Fvibe-report.md&title=Jason+Chen+%E2%80%94+vibe+report" },
            { id: "JohnM-code", student: "John Maida", title: "Comparing AI Tools — SAT vocab app", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-JohnM-code/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-JohnM-code/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-JohnM-code%2Fweek1%2F7_15%2Fvibe-report.md&title=John+Maida+%E2%80%94+vibe+report" },
            { id: "oujustinou", student: "Justin Ou", title: "To-Do List · Three-Tool Comparison", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oujustinou/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-oujustinou/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-oujustinou%2Fweek1%2F7_15%2Fvibe-report.md&title=Justin+Ou+%E2%80%94+vibe+report" },
            { id: "kc2386-rgb", student: "Kylie Cheung", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-kc2386-rgb/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-kc2386-rgb/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-kc2386-rgb%2Fweek1%2F7_15%2Fvibe-report.md&title=Kylie+Cheung+%E2%80%94+vibe+report" },
            { id: "la523-tech", student: "Liam Allen", title: "AI Todo List Comparison Dashboard", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-la523-tech/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-la523-tech/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-la523-tech%2Fweek1%2F7_15%2Fvibe-report.md&title=Liam+Allen+%E2%80%94+vibe+report" },
            { id: "md2367-888", student: "Magnes Dugan", title: "Ultimate Tic Tac Toe", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-md2367-888/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-md2367-888/tree/main/week1/7_15" },
            { id: "oliverc70", student: "Oliver Chung", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oliverc70/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-oliverc70/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-oliverc70%2Fweek1%2F7_15%2Fvibe-report.md&title=Oliver+Chung+%E2%80%94+vibe+report" },
            { id: "or2270", student: "Om Ravula", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-or2270/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-or2270/tree/main/week1/7_15" },
            { id: "sg2697-ux", student: "Sebastien Gournay", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-sg2697-ux/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-sg2697-ux/tree/main/week1/7_15" },
            { id: "vienna-carew", student: "Vienna Carew", title: "Flashcard Lab", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-vienna-carew/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-vienna-carew/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-vienna-carew%2Fweek1%2F7_15%2Fvibe-report.md&title=Vienna+Carew+%E2%80%94+vibe+report" },
            { id: "winnie-monroe", student: "Winnie Monroe", title: "Comparing AI Tools — French quiz", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-winnie-monroe/week1/7_15/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-winnie-monroe/tree/main/week1/7_15", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-winnie-monroe%2Fweek1%2F7_15%2Fvibe-report.md&title=Winnie+Monroe+%E2%80%94+vibe+report" }
        ],
    },
    {
        id: "week2-7_20", kind: 'activity', chip: "W2 Mon", day: "Mon · Jul 20", title: "AI as Moral Assistant",
        entries: [
            { id: "ay487-maker", student: "Ajin Yohannan", title: "Facial Recognition: Privacy vs. Security", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-ay487-maker/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-ay487-maker/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-ay487-maker%2Fweek2%2F7_20%2Fvibe-report.md&title=Ajin+Yohannan+%E2%80%94+vibe+report" },
            { id: "as4663-hash", student: "Aria Sharma", title: "FairShare — Make the work visible", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-as4663-hash/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-as4663-hash/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-as4663-hash%2Fweek2%2F7_20%2Fvibe-report.md&title=Aria+Sharma+%E2%80%94+vibe+report" },
            { id: "ds2553", student: "Derin Sezgin", title: "ClimateHonest | July 20 Project", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-ds2553/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-ds2553/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-ds2553%2Fweek2%2F7_20%2Fvibe-report.md&title=Derin+Sezgin+%E2%80%94+vibe+report" },
            { id: "c28eh-eng", student: "Elaine Huang", title: "Screen Time Cost Converter", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-c28eh-eng/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-c28eh-eng/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-c28eh-eng%2Fweek2%2F7_20%2Fvibe-report.md&title=Elaine+Huang+%E2%80%94+vibe+report" },
            { id: "et483-sys", student: "Emily Tai", title: "Second Life · disposal decision guide", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-et483-sys/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-et483-sys/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-et483-sys%2Fweek2%2F7_20%2Fvibe-report.md&title=Emily+Tai+%E2%80%94+vibe+report" },
            { id: "eb886-ops", student: "Evan Birnbaum", title: "Carbon Honesty + Offset", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-eb886-ops/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-eb886-ops/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-eb886-ops%2Fweek2%2F7_20%2Fvibe-report.md&title=Evan+Birnbaum+%E2%80%94+vibe+report" },
            { id: "isaiah-coder11", student: "Isa Offengenden", title: "The Real Cost of Crime | Educational Resource", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-isaiah-coder11/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-isaiah-coder11/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-isaiah-coder11%2Fweek2%2F7_20%2Fvibe-report.md&title=Isa+Offengenden+%E2%80%94+vibe+report" },
            { id: "br478-spec", student: "Jamin Rose", title: "Before You Post", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-br478-spec/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-br478-spec/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-br478-spec%2Fweek2%2F7_20%2Fvibe-report.md&title=Jamin+Rose+%E2%80%94+vibe+report" },
            { id: "jason-chen3968", student: "Jason Chen", title: "Choose Health — Don't Smoke", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-jason-chen3968/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-jason-chen3968/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-jason-chen3968%2Fweek2%2F7_20%2Fvibe-report.md&title=Jason+Chen+%E2%80%94+vibe+report" },
            { id: "JohnM-code", student: "John Maida", title: "Spectrum Check — read past your own side", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-JohnM-code/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-JohnM-code/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-JohnM-code%2Fweek2%2F7_20%2Fvibe-report.md&title=John+Maida+%E2%80%94+vibe+report" },
            { id: "oujustinou", student: "Justin Ou", title: "RealCrime · Small Crime, Big Consequences", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oujustinou/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-oujustinou/tree/main/week2/7_20" },
            { id: "kc2386-rgb", student: "Kylie Cheung", title: "Carbon Footprint Guide · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-kc2386-rgb/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-kc2386-rgb/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-kc2386-rgb%2Fweek2%2F7_20%2Fvibe-report.md&title=Kylie+Cheung+%E2%80%94+vibe+report" },
            { id: "la523-tech", student: "Liam Allen", title: "The Rebalance Diet", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-la523-tech/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-la523-tech/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-la523-tech%2Fweek2%2F7_20%2Fvibe-report.md&title=Liam+Allen+%E2%80%94+vibe+report" },
            { id: "md2367-888", student: "Magnes Dugan", title: "Wattwise | Everyday Habit Guide", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-md2367-888/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-md2367-888/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-md2367-888%2Fweek2%2F7_20%2Fvibe-report.md&title=Magnes+Dugan+%E2%80%94+vibe+report" },
            { id: "oliverc70", student: "Oliver Chung", title: "Wattwise | Everyday Habit Guide", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oliverc70/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-oliverc70/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-oliverc70%2Fweek2%2F7_20%2Fvibe-report.md&title=Oliver+Chung+%E2%80%94+vibe+report" },
            { id: "or2270", student: "Om Ravula", title: "Vegetarian Food Diary", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-or2270/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-or2270/tree/main/week2/7_20" },
            { id: "sg2697-ux", student: "Sebastien Gournay", title: "The Rebalance Ledger", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-sg2697-ux/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-sg2697-ux/tree/main/week2/7_20" },
            { id: "vienna-carew", student: "Vienna Carew", title: "Kindness, daily", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-vienna-carew/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-vienna-carew/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-vienna-carew%2Fweek2%2F7_20%2Fvibe-report.md&title=Vienna+Carew+%E2%80%94+vibe+report" },
            { id: "winnie-monroe", student: "Winnie Monroe", title: "The Footprint Files", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-winnie-monroe/week2/7_20/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-winnie-monroe/tree/main/week2/7_20", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-winnie-monroe%2Fweek2%2F7_20%2Fvibe-report.md&title=Winnie+Monroe+%E2%80%94+vibe+report" }
        ],
    },
    {
        id: "week2-7_21", kind: 'activity', chip: "W2 Tue", day: "Tue · Jul 21", title: "Red-Teaming Dark Patterns",
        entries: [
            { id: "ay487-maker", student: "Ajin Yohannan", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-ay487-maker/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-ay487-maker/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-ay487-maker%2Fweek2%2F7_21%2Fvibe-report.md&title=Ajin+Yohannan+%E2%80%94+vibe+report" },
            { id: "as4663-hash", student: "Aria Sharma", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-as4663-hash/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-as4663-hash/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-as4663-hash%2Fweek2%2F7_21%2Fvibe-report.md&title=Aria+Sharma+%E2%80%94+vibe+report" },
            { id: "ds2553", student: "Derin Sezgin", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-ds2553/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-ds2553/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-ds2553%2Fweek2%2F7_21%2Fvibe-report.md&title=Derin+Sezgin+%E2%80%94+vibe+report" },
            { id: "c28eh-eng", student: "Elaine Huang", title: "The Delahy Button", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-c28eh-eng/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-c28eh-eng/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-c28eh-eng%2Fweek2%2F7_21%2Fvibe-report.md&title=Elaine+Huang+%E2%80%94+vibe+report" },
            { id: "et483-sys", student: "Emily Tai", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-et483-sys/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-et483-sys/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-et483-sys%2Fweek2%2F7_21%2Fvibe-report.md&title=Emily+Tai+%E2%80%94+vibe+report" },
            { id: "eb886-ops", student: "Evan Birnbaum", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-eb886-ops/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-eb886-ops/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-eb886-ops%2Fweek2%2F7_21%2Fvibe-report.md&title=Evan+Birnbaum+%E2%80%94+vibe+report" },
            { id: "isaiah-coder11", student: "Isa Offengenden", title: "My Dark Pattern Attempts", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-isaiah-coder11/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-isaiah-coder11/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-isaiah-coder11%2Fweek2%2F7_21%2Fvibe-report.md&title=Isa+Offengenden+%E2%80%94+vibe+report" },
            { id: "br478-spec", student: "Jamin Rose", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-br478-spec/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-br478-spec/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-br478-spec%2Fweek2%2F7_21%2Fvibe-report.md&title=Jamin+Rose+%E2%80%94+vibe+report" },
            { id: "jason-chen3968", student: "Jason Chen", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-jason-chen3968/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-jason-chen3968/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-jason-chen3968%2Fweek2%2F7_21%2Fvibe-report.md&title=Jason+Chen+%E2%80%94+vibe+report" },
            { id: "JohnM-code", student: "John Maida", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-JohnM-code/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-JohnM-code/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-JohnM-code%2Fweek2%2F7_21%2Fvibe-report.md&title=John+Maida+%E2%80%94+vibe+report" },
            { id: "oujustinou", student: "Justin Ou", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oujustinou/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-oujustinou/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-oujustinou%2Fweek2%2F7_21%2Fvibe-report.md&title=Justin+Ou+%E2%80%94+vibe+report" },
            { id: "kc2386-rgb", student: "Kylie Cheung", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-kc2386-rgb/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-kc2386-rgb/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-kc2386-rgb%2Fweek2%2F7_21%2Fvibe-report.md&title=Kylie+Cheung+%E2%80%94+vibe+report" },
            { id: "la523-tech", student: "Liam Allen", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-la523-tech/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-la523-tech/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-la523-tech%2Fweek2%2F7_21%2Fvibe-report.md&title=Liam+Allen+%E2%80%94+vibe+report" },
            { id: "md2367-888", student: "Magnes Dugan", title: "Apex Fitness - Signup & Dashboard", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-md2367-888/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-md2367-888/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-md2367-888%2Fweek2%2F7_21%2Fvibe-report.md&title=Magnes+Dugan+%E2%80%94+vibe+report" },
            { id: "oliverc70", student: "Oliver Chung", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oliverc70/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-oliverc70/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-oliverc70%2Fweek2%2F7_21%2Fvibe-report.md&title=Oliver+Chung+%E2%80%94+vibe+report" },
            { id: "or2270", student: "Om Ravula", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-or2270/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-or2270/tree/main/week2/7_21" },
            { id: "sg2697-ux", student: "Sebastien Gournay", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-sg2697-ux/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-sg2697-ux/tree/main/week2/7_21" },
            { id: "vienna-carew", student: "Vienna Carew", title: "AquaVault | Water Bottle Site Hub", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-vienna-carew/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-vienna-carew/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-vienna-carew%2Fweek2%2F7_21%2Fvibe-report.md&title=Vienna+Carew+%E2%80%94+vibe+report" },
            { id: "winnie-monroe", student: "Winnie Monroe", title: "Dark Pattern Lab · Overview", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-winnie-monroe/week2/7_21/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-winnie-monroe/tree/main/week2/7_21", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-winnie-monroe%2Fweek2%2F7_21%2Fvibe-report.md&title=Winnie+Monroe+%E2%80%94+vibe+report" }
        ],
    },
    {
        id: "week2-7_22", kind: 'activity', chip: "W2 Wed", day: "Wed · Jul 22", title: "AI Against AI",
        entries: [
            { id: "ay487-maker", student: "Ajin Yohannan", title: "AI Against AI · Attempts", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-ay487-maker/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-ay487-maker/tree/main/week2/7_22", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-ay487-maker%2Fweek2%2F7_22%2Fvibe-report.md&title=Ajin+Yohannan+%E2%80%94+vibe+report" },
            { id: "as4663-hash", student: "Aria Sharma", title: "Profile Fog", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-as4663-hash/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-as4663-hash/tree/main/week2/7_22" },
            { id: "ds2553", student: "Derin Sezgin", title: "Derin Ege Sezgin | SDG Youth Connect", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-ds2553/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-ds2553/tree/main/week2/7_22" },
            { id: "c28eh-eng", student: "Elaine Huang", title: "Bot Blocker — AI Against AI", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-c28eh-eng/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-c28eh-eng/tree/main/week2/7_22", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-c28eh-eng%2Fweek2%2F7_22%2Fvibe-report.md&title=Elaine+Huang+%E2%80%94+vibe+report" },
            { id: "et483-sys", student: "Emily Tai", title: "SynthSense", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-et483-sys/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-et483-sys/tree/main/week2/7_22" },
            { id: "eb886-ops", student: "Evan Birnbaum", title: "Pattern Flip Pro | Ethical UI Studio", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-eb886-ops/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-eb886-ops/tree/main/week2/7_22", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-eb886-ops%2Fweek2%2F7_22%2Fvibe-report.md&title=Evan+Birnbaum+%E2%80%94+vibe+report" },
            { id: "isaiah-coder11", student: "Isa Offengenden", title: "Redirecting...", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-isaiah-coder11/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-isaiah-coder11/tree/main/week2/7_22", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-isaiah-coder11%2Fweek2%2F7_22%2Fvibe-report.md&title=Isa+Offengenden+%E2%80%94+vibe+report" },
            { id: "br478-spec", student: "Jamin Rose", title: "AI Against AI — Jamin Rose", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-br478-spec/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-br478-spec/tree/main/week2/7_22" },
            { id: "jason-chen3968", student: "Jason Chen", title: "False Fact Injector", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-jason-chen3968/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-jason-chen3968/tree/main/week2/7_22", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-jason-chen3968%2Fweek2%2F7_22%2Fvibe-report.md&title=Jason+Chen+%E2%80%94+vibe+report" },
            { id: "JohnM-code", student: "John Maida", title: "AI vs. AI Assignment", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-JohnM-code/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-JohnM-code/tree/main/week2/7_22", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-JohnM-code%2Fweek2%2F7_22%2Fvibe-report.md&title=John+Maida+%E2%80%94+vibe+report" },
            { id: "oujustinou", student: "Justin Ou", title: "Did an AI write this code? · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oujustinou/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-oujustinou/tree/main/week2/7_22", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-oujustinou%2Fweek2%2F7_22%2Fvibe-report.md&title=Justin+Ou+%E2%80%94+vibe+report" },
            { id: "kc2386-rgb", student: "Kylie Cheung", title: "Your Submission · Ethical Vibe Coding", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-kc2386-rgb/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-kc2386-rgb/tree/main/week2/7_22" },
            { id: "la523-tech", student: "Liam Allen", title: "VeriMedia Inspector", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-la523-tech/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-la523-tech/tree/main/week2/7_22" },
            { id: "md2367-888", student: "Magnes Dugan", title: "Magnes Dugan · Personal Website", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-md2367-888/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-md2367-888/tree/main/week2/7_22" },
            { id: "oliverc70", student: "Oliver Chung", title: "Command Console", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oliverc70/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-oliverc70/tree/main/week2/7_22" },
            { id: "sg2697-ux", student: "Sebastien Gournay", title: "Sebastien Gournay · About Me", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-sg2697-ux/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-sg2697-ux/tree/main/week2/7_22" },
            { id: "vienna-carew", student: "Vienna Carew", title: "Week 2, Day 3 Activities", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-vienna-carew/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-vienna-carew/tree/main/week2/7_22", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-vienna-carew%2Fweek2%2F7_22%2Fvibe-report.md&title=Vienna+Carew+%E2%80%94+vibe+report" },
            { id: "winnie-monroe", student: "Winnie Monroe", title: "AI Against AI · 7/22 Assignment", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-winnie-monroe/week2/7_22/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-winnie-monroe/tree/main/week2/7_22" }
        ],
    },
    {
        id: "week3-7_27", kind: 'activity', chip: "W3 Mon", day: "Mon · Jul 27", title: "Usability Testing",
        entries: [
            { id: "oliverc70", student: "Oliver Chung", title: "Now Screening — Test Reels", url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oliverc70/week3/7_27/code_deliverable/", repo: "https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/class-repo-oliverc70/tree/main/week3/7_27", report: "https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fclass-repo-oliverc70%2Fweek3%2F7_27%2Fvibe-report.md&title=Oliver+Chung+%E2%80%94+vibe+report" }
        ],
    },
    {
        id: "week3-7_28", kind: 'activity', chip: "W3 Tue", day: "Tue · Jul 28", title: "Value Verification",
        entries: [
        ],
    },
    {
        id: 'project1', kind: 'project', chip: 'Proj 1', day: 'Due Mon · Jul 20', title: "Project 1 — Vibe code something your team wants",
        entries: [
            { id: 'meet-in-the-middle', team: "Meet in the Middle", members: "Evan Birnbaum · Derin Sezgin · Magnes Dugan · Oliver Chung",
              blurb: "Finds a fair meeting spot in NYC for a group — everyone enters where they're coming from, it picks the middle.",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/group-project-1-templated-guantanamo-bay-mcdonalds/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/group-project-1-templated-guantanamo-bay-mcdonalds',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fgroup-project-1-templated-guantanamo-bay-mcdonalds%2Fproject-report.md&title=Meet+in+the+Middle+%E2%80%94+project+report' },
            { id: 'study-buddy', team: "Study Buddy", members: "Kylie Cheung · Emily Tai · Aria Sharma",
              blurb: "Turns studying into a learning adventure — a companion that keeps you moving through material.",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/group-project-1-templated-kea/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/group-project-1-templated-kea',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fgroup-project-1-templated-kea%2Fproject-report.md&title=Study+Buddy+%E2%80%94+project+report' },
            { id: 'priorical', team: "PrioriCal", members: "Isa Offengenden · Om Ravula · Jason Chen",
              blurb: "A calendar that prioritizes for you — sorts what actually matters out of a crowded week.",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/group-project-1-templated-team-2/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/group-project-1-templated-team-2',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fgroup-project-1-templated-team-2%2Fproject-report.md&title=PrioriCal+%E2%80%94+project+report' },
            { id: 'payrep', team: "PayRep", members: "Ajin Yohannan · Jamin Rose · John Maida",
              blurb: "Settle up and keep score — tracks who paid last so the next round is obvious.",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/group-project-1-templated-jamin-s-team/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/group-project-1-templated-jamin-s-team',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fgroup-project-1-templated-jamin-s-team%2Fproject-report.md&title=PayRep+%E2%80%94+project+report' },
            { id: 'depop-finder', team: "Depop Finder", members: "Vienna Carew · Winnie Monroe · Elaine Huang",
              blurb: "Secondhand price check — is that resale listing actually a good deal?",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/group-project-1-templated-vew/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/group-project-1-templated-vew',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fgroup-project-1-templated-vew%2Fproject-report.md&title=Depop+Finder+%E2%80%94+project+report' },
            { id: 'food-save', team: "Food Save", members: "Justin Ou · Liam Allen · Sebastien Gournay",
              blurb: "Global culinary abundance — cut food waste by making what you already have into a meal.",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/group-project-1-templated-team-1/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/group-project-1-templated-team-1',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fgroup-project-1-templated-team-1%2Fproject-report.md&title=Food+Save+%E2%80%94+project+report' },
        ],
    },
    { id: 'project2', kind: 'project', chip: 'Proj 2', day: 'Due Mon · Jul 27', title: "Project 2 — Build for a human value",
        entries: [
            { id: "super-duper-amazing-team", team: "Fake Finder", members: "Isa Offengenden · Om Ravula · Jason Chen",
              blurb: "A security checker that flags fake / suspicious accounts so minors stay safer on social media — with a dummy feed to test it on. · value: security",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/group-project-2-templated-super-duper-amazing-team/code_deliverable/fake_finder.html',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/group-project-2-templated-super-duper-amazing-team',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fgroup-project-2-templated-super-duper-amazing-team%2Fproject-report.md&title=Super%20Duper%20Amazing%20Team%20%E2%80%94%20project%20report' },
            { id: "vault-notes", team: "Vault Notes", members: "John Maida · Ajin Yohannan",
              blurb: "A locking journal — a safe, private space for high-schoolers to write. · value: safety",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/group-project-2-templated-jamin-s-2nd-team/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/group-project-2-templated-jamin-s-2nd-team',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fgroup-project-2-templated-jamin-s-2nd-team%2Fproject-report.md&title=Vault%20Notes%20%E2%80%94%20project%20report' },
            { id: "borrow-board", team: "Borrow Board", members: "Emily Tai · Kylie Cheung · Aria Sharma",
              blurb: "Borrow instead of buy — a lending board for college students. · value: sustainability & trust",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/group-project-2-templated-chezborgar/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/group-project-2-templated-chezborgar',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fgroup-project-2-templated-chezborgar%2Fproject-report.md&title=Borrow%20Board%20%E2%80%94%20project%20report' },
            { id: "fixr-findr", team: "Fixr Findr", members: "Evan Birnbaum · Derin Sezgin · Magnes Dugan",
              blurb: "Fix or replace? Estimates repair cost + CO₂ saved so people repair instead of trashing devices. · value: sustainability & transparency",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/group-project-2-templated-guantanamo-bay-wendy-s/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/group-project-2-templated-guantanamo-bay-wendy-s',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fgroup-project-2-templated-guantanamo-bay-wendy-s%2Fproject-report.md&title=Fixr%20Findr%20%E2%80%94%20project%20report' },
            { id: "mypace", team: "MyPace", members: "Elaine Huang · Winnie Monroe · Vienna Carew",
              blurb: "Log meds and share health updates — helping elderly adults living independently stay connected. · value: care",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/group-project-2-templated-we-re-always-two-steps-ahead/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/group-project-2-templated-we-re-always-two-steps-ahead',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fgroup-project-2-templated-we-re-always-two-steps-ahead%2Fproject-report.md&title=MyPace%20%E2%80%94%20project%20report' },
            { id: "justina", team: "Justina", members: "Liam Allen · Justin Ou · Sebastien Gournay",
              blurb: "A focus app for writers and students — stay focused, produce work. · value: productivity",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/group-project-2-templated-liam-justin-sebastien/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/group-project-2-templated-liam-justin-sebastien',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Fgroup-project-2-templated-liam-justin-sebastien%2Fproject-report.md&title=Justina%20%E2%80%94%20project%20report' },
        ],
    },
    {
        // Final teams = the Project 2 teams; each repo is named after the team's
        // value. Apps are due deployed Thursday morning — until a team pushes, the
        // live URL shows the starter placeholder, which is honest enough for now.
        // `deck` is the team's Tuesday pitch deck (Google Slides /preview embeds);
        // three teams sent links so far — paste the rest in as they arrive.
        id: 'final', kind: 'project', chip: 'Final', day: 'Thu · Jul 30', title: "Final Project — Benefit someone outside the class",
        entries: [
            { id: 'sustainability-transparency', team: "AI Footprint Lens", members: "Evan Birnbaum · Derin Sezgin · Magnes Dugan · Oliver Chung",
              blurb: "Makes the hidden environmental footprint of AI use visible. · value: sustainability & transparency",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/final-project-templated-sustainability-transparency/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/final-project-templated-sustainability-transparency',
              deck: 'https://docs.google.com/presentation/d/1qpotoLVihhcyXlwBkzjUyhNaf-6TdGoo/preview',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Ffinal-project-templated-sustainability-transparency%2Fproject-report.md&title=AI+Footprint+Lens+%E2%80%94+project+report' },
            { id: 'care-wellbeing', team: "Care & Wellbeing", members: "Elaine Huang · Winnie Monroe · Vienna Carew",
              blurb: "Final build lands Thursday morning. · value: care & wellbeing",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/final-project-templated-care-wellbeing/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/final-project-templated-care-wellbeing',
              deck: 'https://docs.google.com/presentation/d/1IGt0Swp9Jab8dfQ55K_Sd0ZVqQqBg-KQ/preview',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Ffinal-project-templated-care-wellbeing%2Fproject-report.md&title=Care+%26+Wellbeing+%E2%80%94+project+report' },
            { id: 'productivity', team: "Productivity", members: "Liam Allen · Justin Ou · Sebastien Gournay",
              blurb: "Final build lands Thursday morning. · value: productivity",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/final-project-templated-productivity/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/final-project-templated-productivity',
              deck: 'https://docs.google.com/presentation/d/1qEqyABTX14FNS6b3nc0lpdZHjAvITi4r/preview',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Ffinal-project-templated-productivity%2Fproject-report.md&title=Productivity+%E2%80%94+project+report' },
            { id: 'security', team: "Security", members: "Isa Offengenden · Om Ravula · Jason Chen",
              blurb: "Final build lands Thursday morning. · value: security",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/final-project-templated-security/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/final-project-templated-security',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Ffinal-project-templated-security%2Fproject-report.md&title=Security+%E2%80%94+project+report' },
            { id: 'safety-autonomy', team: "Safety & Autonomy", members: "Jamin Rose · John Maida · Ajin Yohannan",
              blurb: "Final build lands Thursday morning. · value: safety & autonomy",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/final-project-templated-safety-autonomy/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/final-project-templated-safety-autonomy',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Ffinal-project-templated-safety-autonomy%2Fproject-report.md&title=Safety+%26+Autonomy+%E2%80%94+project+report' },
            { id: 'sustainability-trust', team: "Sustainability & Trust", members: "Emily Tai · Kylie Cheung · Aria Sharma",
              blurb: "Final build lands Thursday morning. · value: sustainability & trust",
              url: 'https://cornell-tech-vibe-coding-summer-2026.github.io/final-project-templated-sustainability-trust/code_deliverable/',
              repo: 'https://github.com/Cornell-Tech-Vibe-Coding-Summer-2026/final-project-templated-sustainability-trust',
              report: 'https://vibe-coding-ethics.tech.cornell.edu/instructions.html?file=https%3A%2F%2Fcornell-tech-vibe-coding-summer-2026.github.io%2Ffinal-project-templated-sustainability-trust%2Fproject-report.md&title=Sustainability+%26+Trust+%E2%80%94+project+report' },
        ],
    },
]

// ★ Pinned picks — standout submissions surfaced as the first chip ("★ Picks")
// so visitors see the best work without digging. Reference by set id + entry id
// and add a one-line `note` saying why it's worth a look. Swap these freely —
// they live BELOW the generated array, so refresh_submissions.py never touches
// them (a pick whose entry disappears on refresh is silently skipped).
// A pick may add `url`/`title` to deep-link a specific page inside the
// submission, or skip `set`/`entry` entirely for a standalone link (then give
// student, title, url, and context yourself). No picks from W1 Mon on purpose —
// we don't play favorites with personal portfolio pages.
const FEATURED_PICKS = [
    { set: 'week1-7_15', entry: 'oliverc70', title: "Comparing AI Tools — Claude version",
      url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oliverc70/week1/7_15/code_deliverable/code_deliverable/claude/Claude.html",
      note: "The Claude build from his three-tool comparison." },
    { set: 'week2-7_21', entry: 'kc2386-rgb', note: "Picked for the write-up — open the Report for a sharp red-teaming reflection." },
    { set: 'week2-7_21', entry: 'oujustinou', title: "Hard Unsubscribe",
      url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-oujustinou/week2/7_21/code_deliverable/part2-hard-unsubscribe.html",
      note: "The hard-unsubscribe flow — infuriating by design, which is the point." },
    { set: 'week2-7_21', entry: 'et483-sys', note: "Documents the requests the AI actually rejected — read the write-up." },
    { student: "Aria Sharma", title: "Course repo — all write-ups", context: "Overall",
      url: "https://cornell-tech-vibe-coding-summer-2026.github.io/class-repo-as4663-hash/",
      note: "Consistently great write-ups across the whole course." },
]

// ★ Per-day picks (Hauke's grading favorites): starred and sorted first inside
// their day's row. Keyed by set id → student handles; handles that aren't in
// the set (page not live) are simply ignored, so this survives refreshes.
// Deliberately no W1 Mon list — we don't play favorites with personal portfolios.
const DAY_PICKS = {
    'week1-7_14': ['jason-chen3968', 'oliverc70', 'or2270', 'kc2386-rgb', 'vienna-carew'],
    'week1-7_15': ['as4663-hash', 'ds2553', 'c28eh-eng', 'eb886-ops', 'oujustinou', 'la523-tech', 'or2270', 'vienna-carew', 'winnie-monroe', 'oliverc70'],
    'week2-7_20': ['as4663-hash', 'c28eh-eng', 'et483-sys', 'eb886-ops', 'isaiah-coder11', 'br478-spec', 'JohnM-code', 'oujustinou', 'la523-tech', 'md2367-888', 'vienna-carew', 'winnie-monroe'],
    'week2-7_21': ['isaiah-coder11', 'br478-spec', 'JohnM-code', 'oujustinou', 'la523-tech', 'oliverc70', 'vienna-carew', 'winnie-monroe', 'kc2386-rgb', 'et483-sys'],
    'week2-7_22': ['ay487-maker', 'as4663-hash', 'c28eh-eng', 'br478-spec', 'oujustinou', 'kc2386-rgb', 'vienna-carew', 'winnie-monroe'],
}
for (const [setId, handles] of Object.entries(DAY_PICKS)) {
    const set = SUBMISSION_SETS.find((s) => s.id === setId)
    if (!set) continue
    set.entries.forEach((e) => { e.featured = handles.includes(e.id) })
    // Stable sort: picks lead the row, alphabetical order kept within each half.
    set.entries.sort((a, b) => (b.featured ? 1 : 0) - (a.featured ? 1 : 0))
}

export const FEATURED_SET = {
    id: 'featured', kind: 'featured', chip: '★ Picks', day: 'Instructor picks', title: "Some favorites from the class",
    entries: FEATURED_PICKS.flatMap((p, i) => {
        if (!p.set) return [{ id: `pick-${i}`, student: p.student, title: p.title, url: p.url, blurb: p.note, context: p.context }]
        const src = SUBMISSION_SETS.find((s) => s.id === p.set)
        const e = src?.entries.find((x) => x.id === p.entry)
        return e ? [{ ...e, ...(p.url && { url: p.url }), ...(p.title && { title: p.title }),
                      id: `pick-${i}`, student: e.student || e.team, blurb: p.note, context: `${src.chip} · ${src.title}` }] : []
    }),
}

// Sets with no entries yet render a "posted after class" placeholder.
export const hasEntries = (set) => Array.isArray(set.entries) && set.entries.length > 0
